# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SdkDemoFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
      pod ’sdkDemo’,:path => ‘../sdkDemo’
  # Pods for SdkDemoFramework

  target 'SdkDemoFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
